apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasisbot
  labels:
    app: oasisbot
spec:  
  selector:
    matchLabels:
      app: oasisbot
  template:
    metadata:
      labels:
        app: oasisbot
    spec:
      containers:
      - name: oasisbot
        image: robmaynardjr/oasisbot:latest
      imagePullSecrets:
      - name: dockercred2
        
